{{- if .Values.configs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}-env
  labels:
    {{- include "prometheus-exporter.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
data:
  {{- with .Values.configs }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
