{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-exporter.fullname" . }}-secret
  labels:
    {{- include "prometheus-exporter.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
stringData:
  {{- with .Values.secrets }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
